let chatCount = 0, codeCount = 0, imageCount = 0;
const chatOutput = document.getElementById('chat-output');
const codeOutput = document.getElementById('code-output');
const imageOutput = document.getElementById('image-output');
const chatInput = document.getElementById('chat-input');
const codeInput = document.getElementById('code-input');
const imageInput = document.getElementById('image-input');
const chatCountDisplay = document.getElementById('chat-count');
const codeCountDisplay = document.getElementById('code-count');
const imageCountDisplay = document.getElementById('image-count');

const chatResponses = {
  'what is ai': 'AI mimics human thinking, like problem-solving or learning. I’m your chill Baked AI buddy! 🌿',
  'code a website': 'Describe a site, like "portfolio with navbar", and I’ll generate it!',
  'default': 'Cool question: "{input}"! I’m mock AI—try something specific! 🌿'
};
const codeTemplates = {
  'portfolio': `<!-- Portfolio Website -->
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <style>
    body {font-family:Arial;background:#f0f0f0;}
    nav {background:#1a3c34;padding:10px;}
    nav a {color:white;margin:0 15px;text-decoration:none;}
    .hero {text-align:center;padding:50px;background:#a3c68c;}
  </style>
</head>
<body>
  <nav><a href="#home">Home</a><a href="#about">About</a><a href="#projects">Projects</a></nav>
  <div class="hero"><h1>Welcome to My Portfolio</h1><p>Showcasing my work with style!</p></div>
</body>
</html>`,
  'blog': `<!-- Blog Website -->
<!DOCTYPE html>
<html>
<head>
  <title>My Blog</title>
  <style>
    body {font-family:Arial;background:#e6f0ea;}
    .post {margin:20px;padding:20px;background:white;border-radius:5px;}
  </style>
</head>
<body>
  <h1>My Blog</h1><div class="post"><h2>First Post</h2><p>Welcome to my blog, powered by Baked AI! 🌿</p></div>
</body>
</html>`,
  'default': `<!-- Website for "{input}" -->
<!DOCTYPE html>
<html>
<head>
  <title>{input}</title>
  <style>
    body {font-family:Arial;background:#f0f0f0;text-align:center;padding:50px;}
    h1 {color:#1a3c34;}
  </style>
</head>
<body>
  <h1>{input}</h1><p>Generated by Baked AI! 🌿</p>
</body>
</html>`
};
const imageUrls = [
  'https://images.unsplash.com/photo-1535893574236-2e2e249a5122?auto=format&fit=crop&w=300', // Lion
  'https://images.unsplash.com/photo-1602491459074-51e0e2f7d71e?auto=format&fit=crop&w=300', // Eagle
  'https://images.unsplash.com/photo-1558917944-8b6d5b7a6e8b?auto=format&fit=crop&w=300'  // Panda
];
let currentImageIndex = 0;

window.onload = () => {
  const savedChats = localStorage.getItem('bakedAIChats');
  if (savedChats) {
    chatOutput.innerHTML = savedChats;
    chatCount = chatOutput.querySelectorAll('p').length / 2;
    chatCountDisplay.textContent = chatCount;
  }
  document.querySelectorAll('.tab').forEach(tab => {
    tab.addEventListener('click', () => {
      document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
      document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
      tab.classList.add('active');
      document.getElementById(tab.dataset.tab).classList.add('active');
    });
  });
  document.getElementById('theme-toggle').addEventListener('click', () => {
    document.body.classList.toggle('light');
    const icon = document.getElementById('theme-toggle').querySelector('i');
    icon.classList.toggle('fa-moon');
    icon.classList.toggle('fa-sun');
  });
};

function debounce(func, wait) {
  let timeout;
  return function(...args) {
    clearTimeout(timeout);
    timeout = setTimeout(() => func.apply(this, args), wait);
  };
}

function handleChat() {
  const input = chatInput.value.trim().toLowerCase();
  if (!input) {
    chatOutput.innerHTML += '<p class="error">Please type a question!</p>';
    return;
  }
  chatCount++;
  const response = chatResponses[input] || chatResponses['default'].replace('{input}', input);
  chatOutput.innerHTML += `<p><b>You:</b> ${input} <button class="copy-btn" onclick="copyText(this)">Copy</button></p><p><b>Baked AI:</b> ${response} <button class="copy-btn" onclick="copyText(this)">Copy</button></p>`;
  chatCountDisplay.textContent = chatCount;
  localStorage.setItem('bakedAIChats', chatOutput.innerHTML);
  chatOutput.scrollTop = chatOutput.scrollHeight;
  chatInput.value = '';
}

function clearChat() {
  chatOutput.innerHTML = '';
  chatCount = 0;
  chatCountDisplay.textContent = chatCount;
  localStorage.removeItem('bakedAIChats');
}

function downloadChat() {
  const blob = new Blob([chatOutput.textContent || 'No chats yet!'], {type: 'text/plain'});
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'baked-ai-chat.txt';
  a.click();
  URL.revokeObjectURL(url);
}

function handleCodeGen() {
  const input = codeInput.value.trim().toLowerCase();
  if (!input) {
    codeOutput.innerHTML += '<pre class="error">Please describe a website!</pre>';
    return;
  }
  codeCount++;
  const template = codeTemplates[input.split(' ')[0]] || codeTemplates['default'].replace('{input}', input);
  codeOutput.innerHTML += `<pre>${template}<button class="copy-btn" onclick="copyText(this)">Copy</button></pre>`;
  codeCountDisplay.textContent = codeCount;
  codeOutput.scrollTop = codeOutput.scrollHeight;
  codeInput.value = '';
}

function downloadCode() {
  const blob = new Blob([codeOutput.textContent || 'No code generated yet!'], {type: 'text/plain'});
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'baked-ai-code.txt';
  a.click();
  URL.revokeObjectURL(url);
}

function handleImageGen() {
  imageCount++;
  currentImageIndex = (currentImageIndex + 1) % imageUrls.length;
  imageOutput.innerHTML = `<img src="${imageUrls[currentImageIndex]}" alt="Animal ${currentImageIndex}" loading="lazy"><p><b>Prompt:</b> Cool animal ${currentImageIndex + 1} <button class="copy-btn" onclick="copyText(this)">Copy</button></p>`;
  imageCountDisplay.textContent = imageCount;
  imageOutput.scrollTop = imageOutput.scrollHeight;
  imageInput.value = 'next';
}

function downloadImagePrompt() {
  const blob = new Blob([imageOutput.textContent || 'No prompts generated yet!'], {type: 'text/plain'});
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'baked-ai-image-prompts.txt';
  a.click();
  URL.revokeObjectURL(url);
}

function copyText(btn) {
  const text = btn.parentElement.textContent.replace('Copy', '').trim();
  navigator.clipboard.writeText(text).then(() => {
    btn.textContent = 'Copied!';
    setTimeout(() => btn.textContent = 'Copy', 2000);
  });
}
